name = "play-jonny-casino-at"
compatibility_date = "2025-01-01"
pages_build_output_dir = "."

[vars]
REF_URL = "https://serffigxjssvpeo.help/RC2TZM?sub_id_3=play-jonny-casino.at"
HMAC_KEY = "10bb2c93d8cf7c3fb9147350882f50e972a733c2c9a11475597c0eae6f38a001"
COOKIE_NAME = "h1s"
PLAY_PATH = "explore"
BUTTON_ID = "p19f32f10bc2babaf4312730e60fc99df"
GATE_SALT = "47abab73f0333797"
GO_URLS = "[\"https://monitorre.top/go/ref\", \"https://firespot.click/go/ref\", \"https://fintechfox.click/go/ref\", \"https://buffout.click/go/ref\"]"
GO_TOKEN = "6c27a2676e6fb97970145a1c9daa1d717ea137c80518a24c"
GO_COOKIE = "ryl9"
CTA_SELECTOR = ".play-button"
